spring.application.name=api-gateway
server.port=8080

spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# USER SERVICE ROUTE
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# parking space routes
spring.cloud.gateway.server.webmvc.routes[1].id=parking-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://PARKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/parking-service/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

#Vehicle service routes
spring.cloud.gateway.server.webmvc.routes[2].id=vehicle-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://VEHICLE-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/vehicle-service/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1